from neural_logic_entropy.util.atom_enum import atoms

excel_header = ["input/" + atoms[0],
                "input/" + atoms[1],
                "input/" + atoms[2],
                "input/" + atoms[3],
                "input/" + atoms[4],
                "input/" + atoms[5],
                "input/" + atoms[6],
                "input/" + atoms[7],
                "input/" + atoms[8],
                "input/" + atoms[9],
                "input/" + atoms[10],
                "input/" + atoms[11],
                "input/" + atoms[12],
                "input/" + atoms[13],
                "input/" + atoms[14],
                "input/" + atoms[15],
                "input/" + atoms[16],
                "input/" + atoms[17],
                "input/" + atoms[18],
                "input/" + atoms[19],
                "output/" + atoms[0],
                "output/" + atoms[1],
                "output/" + atoms[2],
                "output/" + atoms[3],
                "output/" + atoms[4],
                "output/" + atoms[5],
                "output/" + atoms[6],
                "output/" + atoms[7],
                "output/" + atoms[8],
                "output/" + atoms[9],
                "output/" + atoms[10],
                "output/" + atoms[11],
                "output/" + atoms[12],
                "output/" + atoms[13],
                "output/" + atoms[14],
                "output/" + atoms[15],
                "output/" + atoms[16],
                "output/" + atoms[17],
                "output/" + atoms[18],
                "output/" + atoms[19],
                ]
